name: wmp_fe
description: Weekly Meal Planner frontend code.
version: 1.0.0
repository: https://github.com/my_org/wmp_fe

environment:
  sdk: ">=2.19.3 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.0
  lints: ^2.0.0
